name: Android-Remote

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -gpu swiftshader_indirect

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=android-emulator

      - name: Run VNC Server on Emulator
        run: |
          # example: use scrcpy or xvnc to expose emulator screen
          sudo apt-get install -y tigervnc-standalone-server
          vncserver :1 -geometry 1080x1920 -depth 24
