name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP + Create User
        run: |
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Strong password (meets GitHub Windows domain policy)
          $password = "RdpPassw0rd!23456789Xy"
          $sec = ConvertTo-SecureString $password -AsPlainText -Force

          # Create or reset user
          if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
            New-LocalUser "RDP" -Password $sec -AccountNeverExpires
          } else {
            Set-LocalUser -Name "RDP" -Password $sec
          }
          Add-LocalGroupMember "Administrators" "RDP"
          Add-LocalGroupMember "Remote Desktop Users" "RDP"

          # Show connection info
          $pubIP = (Invoke-WebRequest -Uri "https://api.ipify.org").Content
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "IP Address : $pubIP"
          Write-Host "Username   : RDP"
          Write-Host "Password   : $password"
          Write-Host "===================`n"

      - name: Keep Alive
        run: |
          while ($true) {
            Write-Host "[$(Get-Date)] RDP Active"
            Start-Sleep -Seconds 300
          }
