name: Windows RDP VPS

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up RDP user (password = 1)
      run: |
        $password = "1"
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force
        if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
        } else {
            Set-LocalUser -Name "RDP" -Password $securePass
        }
        Add-LocalGroupMember -Group "Administrators" -Member "RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"

        echo "RDP user created with password '1'"

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        echo "RDP enabled."

    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn' -Wait
        echo "Tailscale installed."

    - name: Authenticate Tailscale
      run: |
        & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey ${{ secrets.TS_AUTHKEY }} --accept-routes
        & 'C:\Program Files\Tailscale\tailscale.exe' ip -4
