name: Windows RDP VPS

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up RDP user (password = 1)
      run: |
        $password = "1"
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force
        if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
        } else {
            Set-LocalUser -Name "RDP" -Password $securePass
        }
        Add-LocalGroupMember -Group "Administrators" -Member "RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
        echo "RDP_PASSWORD=1" >> $env:GITHUB_ENV

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn' -Wait

    - name: Authenticate Tailscale
      run: |
        & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey ${{ secrets.TS_AUTHKEY }} --accept-routes
        $tsIP = & 'C:\Program Files\Tailscale\tailscale.exe' ip -4
        echo "TS_IP=$tsIP" >> $env:GITHUB_ENV

    - name: Show RDP credentials
      run: |
        Write-Host "=== RDP ACCESS ==="
        Write-Host "Address: $env:TS_IP"
        Write-Host "Username: RDP"
        Write-Host "Password: $env:RDP_PASSWORD"
        Write-Host "=================="
        while ($true) { Start-Sleep -Seconds 300 }
